[package]
name = "distribution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_toml = "0.14.0"
npm-package-json = "0.1.3"
serde = "1.0.152"
serde_json = "1.0.91"
serde_toml = "0.0.1"
